### PR TITLE
Fixes 4.5.2 model.adoc build problems

### PR DESCRIPTION
**Pull request by apinnick**
Changes:

- Replace "don't" with "do not" so that IDs won't break
- Removed anchor ID that was interfering with another anchor above it.

### CODE REVIEW

**Review by emarcusRH — APPROVED** [review]
/lgtm

**Comment by emarcusRH** [comment]
@oliel  Ori, please review and merge this PR and then regenerate the model

**Review by oliel — APPROVED** [review]

**Review by oliel — APPROVED** [review]

**Review by mwperina — APPROVED** [review]
+1

**Comment by mwperina** [comment]
Please resolve conflicts and rebase on top of master, so we can merge

**Comment by apinnick** [comment]
Cherrypicked changes to new PR: https://github.com/oVirt/ovirt-engine-api-model/pull/87/

**Pull request closed without merging**
